// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: user.proto

package user_client

import (
	"context"

	"user/rpc/pb/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Base            = user.Base
	GetUserInfoReq  = user.GetUserInfoReq
	GetUserInfoResp = user.GetUserInfoResp
	UserInfo        = user.UserInfo

	User interface {
		// 定义一个 GetUserInfo 一元 rpc 方法，请求体和响应体必填。
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 定义一个 GetUserInfo 一元 rpc 方法，请求体和响应体必填。
func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}
