Name: user.rpc
ListenOn: 0.0.0.0:9000
Etcd:
  Hosts:
    - etcd:2379
  Key: user.rpc

Mysql:
  DataSource: root:single_deploy@tcp(mysql:3306)/single_deploy?charset=utf8&parseTime=true&loc=Asia%2FShanghai

CacheConf:
  - Name: cache
    Host: redis:6379
    User: default
    Pass: single_deploy
    DB: 0
